# Copyright Amazon.com Inc. or its affiliates.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: ADF CloudFormation Sample Template (IAM)
Metadata:
  License: Apache-2.0

Parameters:
  DeploymentAssetS3BucketName:
    Type: "String"
    Description: "The S3 Bucket name where deployment assets will be located"

  DeploymentAssetKMSKeyArn:
    Type: "String"
    Description: "The KMS Key Arn with which deployment assets will encrypted"

Resources:
  DevelopersIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: adf-sample-developers-group
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSServiceCatalogEndUserFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCloud9User"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationReadOnlyAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSCodeCommitFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonS3ReadOnlyAccess"

  GlobalInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref "GlobalInstanceRole"

  GlobalInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref DefaultInstanceManagedPolicy
      RoleName: "global-instance-role"

  DefaultInstanceManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Managed policy for default rights needed for EC2 instances"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "autoscaling:Describe*"
              - "autoscaling:EnterStandby"
              - "autoscaling:ExitStandby"
              - "autoscaling:SetInstanceHealth"
              - "autoscaling:UpdateAutoScalingGroup"
              - "cloudformation:SignalResource"
              - "ec2:DescribeTags"
              - "elasticloadbalancing:DeregisterTargets"
              - "elasticloadbalancing:DescribeTargetGroups"
              - "elasticloadbalancing:DescribeTargetHealth"
              - "elasticloadbalancing:RegisterTargets"
            Resource:
              - "*"
          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
            Resource:
              - !Ref DeploymentAssetKMSKeyArn
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${DeploymentAssetS3BucketName}/adf-upload/*"
              - !Sub "arn:${AWS::Partition}:s3:::${DeploymentAssetS3BucketName}/adf-pipeline-*"

  CodeDeployServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSCodeDeployRole"
      RoleName: "codedeploy-service-role"

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
          Action: sts:AssumeRole

Outputs:
  DevelopersIAMGroup:
    Description: The ARN of the Developers IAM Group to be exported.
    Export:
      Name: SampleDevelopersIAMGroupArn
    Value: !GetAtt DevelopersIAMGroup.Arn

  GlobalInstanceProfileArn:
    Description: The Arn of the EC2 Instance Profile to be exported.
    Export:
      Name: GlobalInstanceProfileArn
    Value: !GetAtt GlobalInstanceProfile.Arn

  CodeDeployServiceRoleArn:
    Description: The Arn of the CodeDeploy IAM Role to be exported.
    Export:
      Name: CodeDeployServiceRoleArn
    Value: !GetAtt CodeDeployServiceRole.Arn

  ApiGatewayCloudWatchRoleArn:
    Description: The ARN of the API Gateway IAM Role Arn to be exported.
    Export:
      Name: ApiGatewayCloudWatchRoleArn
    Value: !GetAtt ApiGatewayCloudWatchRole.Arn

  DefaultInstanceManagedPolicyArn:
    Description: >-
      The Arn of the Default EC2 Instance Managed Policy to be
      imported into application stacks
    Export:
      Name: DefaultInstanceManagedPolicyArn
    Value: !Ref DefaultInstanceManagedPolicy
