# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - BASH_EXEC
  - CLOUDFORMATION_CFN_LINT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JSON_V8R
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - TERRAFORM_TFLINT
  - YAML_YAMLLINT

SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

# Install plugin for list handling.
JSON_PRETTIER_PRE_COMMANDS:
  - command: |
      npm install -g prettier-plugin-multiline-arrays@1.1.4
      npm install --prefix /node-deps/ prettier-plugin-multiline-arrays@1.1.4
    cwd: "workspace"

CLOUDFORMATION_CFN_LINT_CONFIG_FILE: '.cfnlintrc'
CLOUDFORMATION_CFN_LINT_FILE_EXTENSIONS: [".yml", ".yaml"]
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: '.ecrc.json'
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: '-q'
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
SPELL_CSPELL_ARGUMENTS: '--gitignore --no-progress --show-suggestions'
SPELL_CSPELL_FILE_EXTENSIONS: ["*"]
TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN

GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
