# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - BASH_EXEC
  - CLOUDFORMATION_CFN_LINT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JSON_V8R
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - TERRAFORM_TFLINT
  - YAML_YAMLLINT

# DISABLE:
#   - COPYPASTE # Comment to enable checks of excessive copy-pastes
#   - SPELL # Comment to enable checks of spelling mistakes

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

# Install pluging for list handling.
JSON_PRETTIER_PRE_COMMANDS:
  - command: npm install prettier-plugin-multiline-arrays@1.1.0
    cwd: "workspace"

CLOUDFORMATION_CFN_LINT_CONFIG_FILE: '.cfnlintrc'
CLOUDFORMATION_CFN_LINT_FILE_EXTENSIONS: [".yml", ".yaml"]
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: '.ecrc.json'
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: '-q'
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
SPELL_CSPELL_ARGUMENTS: '--unique --words-only --gitignore'
SPELL_CSPELL_FILE_EXTENSIONS: ["*"]