version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      python: 3.11

  build:
    commands:
      - bash build/docker.sh

  post_build:
    commands:
      - bash build/generate_parameters.sh

artifacts:
  files: '**/*'
