# Copyright Amazon.com Inc. or its affiliates.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - bash build/docker.sh

  post_build:
    commands:
      - bash build/generate_parameters.sh

artifacts:
  files:
    - 'template.yml'
    - 'params/*.json'
    - 'params/*.yml'
