# Copyright Amazon.com Inc. or its affiliates.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: ADF CloudFormation Sample Template (Service Catalog Product)
Metadata:
  License: Apache-2.0

Parameters:
  ProductXTemplateURL:
    Type: String
    Description: Service Catalog CloudFormation Template URL

Resources:
  Portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      AcceptLanguage: en
      Description: Portfolio containing sample Service Catalog products
      DisplayName: Sample Portfolio
      ProviderName: Company

  SampleTagOption:
    Type: "AWS::ServiceCatalog::TagOption"
    Properties:
      Key: "ProductType"
      Value: "Storage"

  SamplePortfolioTagOptionAssociation:
    Type: "AWS::ServiceCatalog::TagOptionAssociation"
    Properties:
      ResourceId: !Ref Portfolio
      TagOptionId: !Ref SampleTagOption

  SampleProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      AcceptLanguage: en
      Description: CloudFormation Template to deploy a sample S3 bucket
      Distributor: Company
      Name: Sample S3 Bucket
      Owner: Company
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Ref ProductXTemplateURL
      SupportDescription: For help with this sample product contact us
      SupportEmail: john@example.com
      SupportUrl: http://example.com

  Association:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      AcceptLanguage: en
      PortfolioId: !Ref Portfolio
      ProductId: !Ref SampleProduct

  SamplePortfolioPrincipalAssociation:
    Type: "AWS::ServiceCatalog::PortfolioPrincipalAssociation"
    Properties:
      PortfolioId: !Ref Portfolio
      PrincipalARN: !ImportValue SampleDevelopersIAMGroupArn
      PrincipalType: "IAM"
