version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - mvn clean package --quiet

artifacts:
  discard-paths: yes  # yamllint disable-line rule:truthy
  files:
    - target/*
    - scripts/*
    - appspec.yml
