pipelines:  
  - name: sample-vpc
    type: cc-cloudformation
    action: create_update
    params:
      - SourceAccountId: 558421765047
      - NotificationEndpoint: bundyf@amazon.com
    targets:
      - /insurance/development
      - approval
      - /insurance/production

  - name: ami-builder
    type: cc-buildonly
    params:
      - ScheduleExpression: rate(7 days)
      - SourceAccountId: 558421765047
      - NotificationEndpoint: bundyf@amazon.com
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-bastion
    type: cc-cloudformation
    action: create_update
    params:
      - SourceAccountId: 558421765047
      - NotificationEndpoint: bundyf@amazon.com
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-alerts
    type: cc-cloudformation
    action: create_update
    params:
      - SourceAccountId: 558421765047
      - NotificationEndpoint: bundyf@amazon.com
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-jenkins
    type: cc-cloudformation
    params:
      - SourceAccountId: 558421765047
      - NotificationEndpoint: bundyf@amazon.com
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-ecr-repository
    type: cc-cloudformation
    params:
      - SourceAccountId: 558421765047
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-logging
    type: cc-cloudformation
    params:
      - SourceAccountId: 558421765047
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-kms
    type: cc-cloudformation
    params:
      - SourceAccountId: 558421765047
    targets:
      - path: 361473679486
        name: deployment-account

  - name: sample-cloudtrail
    type: cc-cloudformation
    params:
      - SourceAccountId: 558421765047
    targets:
      - path: 361473679486
        name: deployment-account