version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
      - pip install -r adf-build/requirements.txt -q
      - python adf-build/generate_params.py
      
  build:
    commands:
      - pip install rdk
      - cd config-rules
      - rdk create-rule-template --rules-only -a  -o template-config-rules.json
      - mv ./template-config-rules.json ..
      - cd ..
artifacts:
  files: '**/*'
