version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - bash build/generate_parameters.sh
      - bash adf-build/helpers/package_transform.sh
artifacts:
  files: '**/*'