version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.0.10" # terraform version. The module support terraform version greater than 0.13.0.
phases:
  install:
    commands:
      - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
      - export PATH=$PATH:$(pwd)
      - bash adf-build/helpers/terraform/install_terraform.sh
      - pip install -r adf-build/requirements.txt -q
  build:
    commands:
      - python adf-build/generate_params.py

artifacts:
  files: "**/*"
